name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install asciinema (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y asciinema

    - name: Install asciinema (macOS)
      if: runner.os == 'macOS'
      run: brew install asciinema

    - name: Verify asciinema installation
      run: asciinema --version

    - name: Build
      run: npm run build

    - name: Test CLI commands
      run: |
        # Test basic CLI functionality
        node dist/index.js --help
        node dist/index.js --version
        node dist/index.js doctor
        
        # Test init command in temporary directory
        mkdir -p test-project
        cd test-project
        node ../dist/index.js init --help
        cd ..
        rm -rf test-project

    - name: Test package installation
      run: |
        npm pack
        npm install -g ./deepguide-ai-dg-*.tgz
        dg --version
        dg doctor
        npm uninstall -g @deepguide-ai/dg

  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Check TypeScript
      run: npm run build

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Audit dependencies
      run: npm audit