name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    name: Validate Demos
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Install asciinema
      run: |
        sudo apt-get update
        sudo apt-get install -y asciinema

    - name: Build
      run: npm run build
    
    - name: Validate demos
      run: node dist/index.js validate
