name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            asset_name: dg-linux
          - os: macos-latest
            platform: macos
            asset_name: dg-macos
          - os: windows-latest
            platform: windows
            asset_name: dg-windows.exe

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build CLI
      run: npm run build

    - name: Build Executables
      run: npm run pkg

    - name: Test Binary
      run: |
        # Basic smoke test
        node dist/index.js --version
        node dist/index.js --help

    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.asset_name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Download all executables
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dg-linux/dg-linux
          dg-macos/dg-macos
          dg-windows/dg-windows.exe
        draft: false
        prerelease: false

        body: |
          ## DeepGuide CLI ${{ steps.get_version.outputs.VERSION }}

          ### Installation
          1. Download the appropriate binary for your platform
          2. Make it executable (Linux/macOS): `chmod +x dg-*`
          3. Move it to your PATH: `sudo mv dg-* /usr/local/bin/dg`

          ### Supported Platforms
          - Linux (x64)
          - macOS (x64, arm64)
          - Windows (x64)

          ### Dependencies
          - asciinema (required for recording demos)

          For full installation instructions, see the [documentation](https://github.com/deepguide-ai/dg/blob/main/README.md). 