name: Test Release Build

on:
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  test-build-executables:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        target:
          - { name: 'darwin-arm64', displayName: 'macOS (Apple Silicon)' }
          - { name: 'darwin-x64', displayName: 'macOS (Intel)' }
          - { name: 'linux-x64', displayName: 'Linux (x64)' }
          - { name: 'windows-x64', displayName: 'Windows (x64)' }
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build executable for ${{ matrix.target.displayName }}
      run: bun run build:exe:${{ matrix.target.name }}
    
    - name: Test executable
      if: matrix.target.name == 'linux-x64'
      run: |
        chmod +x dist/dg-${{ matrix.target.name }}
        ./dist/dg-${{ matrix.target.name }} --help
        ./dist/dg-${{ matrix.target.name }} --version
    
    - name: Check file size
      run: |
        if [[ "${{ matrix.target.name }}" == "windows-x64" ]]; then
          ls -lh dist/dg-${{ matrix.target.name }}
        else
          ls -lh dist/dg-${{ matrix.target.name }}
        fi
        echo "✅ Executable built successfully for ${{ matrix.target.displayName }}" 